apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: repobridge
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: prod
  source:
    repoURL: git@gitlab.com:elenche-devops/infrastellar.git
    targetRevision: main
    path: app-of-apps/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: repobridge
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: dev
  source:
    repoURL: git@gitlab.com:elenche-devops/infrastellar.git
    targetRevision: main
    path: app-of-apps/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: repobridge
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: test
  source:
    repoURL: git@gitlab.com:elenche-devops/infrastellar.git
    targetRevision: main
    path: app-of-apps/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true 
    syncOptions:
    - CreateNamespace=true